version: "3.7"
services:

        postgressql:
         image: postgres
         container_name: postgressql
         env_file:
          - .env
         ports:
          - 5432:5432
         volumes:
          - ./pgdata:/var/lib/postgresql/data
volumes:
        pgdata:

