version: "3.7"
services:
	postgressql:
		image: postgres
		container_name: postgres-sql
		env_file:
			- .env
		ports:
			- 5432:5432
		volumes:
			- database-data:/var/lib/postgresql/data/

volumes:
  pgdata: