version: "3.7"
services:

        postgressql:
         image: postgres
         container_name: postgressql
         environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=changeme
          - POSTGRES_DB=postgres
         ports:
          - 5432:5432
         volumes:
          - ./pgdata:/var/lib/postgresql/data
          
volumes:
        pgdata:



