version: '3.7'
services:
  mongodb-primary:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=mongodb
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=changeme
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/var/lib/mongo-data/data
      
volumes:
  mongo-data:

